server:
  port: 8761
eureka:
  instance:
    hostname: instance
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@133.186.220.58:8761/eureka/
